### ISSUE TITLE
Scales gone

### ISSUE THREAD

**Issue by teo1978** [google/google-visualization-issues#2673]
In our website we have line charts that used to have scaled and now the scales are gone.

We haven't changed anything.

I haven't even looked into it yet. Maybe we are not explicitly setting the scales and they used to be displayed by default and now they aren't. I don't care. Whether it's intended or not, this is a change that **BREAKS BACKWARD COMPATIBILITY**, it breaks webpages that used to work, and as such is an issue that **must be fixed**. Urgently.

![image](https://user-images.githubusercontent.com/542107/46625139-16238f80-cb33-11e8-9381-e498367efd19.png)

I f***ing hate when stuff that has been working for years and hasn't been touched in months suddenly breaks.

**Comment by dlaliberte** [comment]
There was an update last week of Google Charts to v46.  There are some issues with date-time axes that will be fixed soon.  No one complained during 2 weeks of testing (on 'upcoming'), hence the errors propagate to release before people start noticing.

If you hate the occasional breakage that much, and are not going to be testing upcoming versions, then you should probably freeze what you load to a particular version.  You want '45.2' instead of 'current'.

**Comment by teo1978** [comment]
I see, thank you for the workaround.

I have just found out that the issue appear if the height of the chart is below a given size. If I make it higher, it works as expected.

It's not just the date/time axis, btw, the vertical axis too.

On the horizontal (i.e. time)  axis we have 'gridlines' set explicitly.

**Comment by php4fan** [comment]
> There are some issues with date-time axes that will be fixed soon

So are they fixed now?

**Comment by dlaliberte** [comment]
The problem with missing axis ticks and gridlines caused by not enough space (and a few other related causes) is not solved.  That will require a larger refactoring to keep track of the best of the failed attempts.

**Comment by php4fan** [comment]
Well this is urgent.

I am now stuck with that old version because with tha latest one I get no scales.
However, the old version has huge issues which are already fixed in later versions.

**Comment by php4fan** [comment]
Is there any workaround at all, like some parameter that explicitly forces scales to be rendered regardless of available space?

**Comment by dlaliberte** [comment]
There is no workaround to force drawing axis ticks if they don't fit.  Why is it not possible for you to use the height, width, and chartArea options to specify enough space?  For chartArea, there are options for height, width, top, bottom, left, and right.

**Comment by php4fan** [comment]
My graph are the same size they used to be.
If there is enough space for the old version to include axis ticks and values, there should be enough space for the new version too.

Actually I have observed that, on slightly bigger graphs, where both the old and the new version draw ticks and scales, in some cases the older version does a better job (though in other cases it's the other way round as one would expect).

**Comment by dlaliberte** [comment]
I would guess that the older version that is showing axis ticks in your case is actually hiding some parts in the rendering pass.  That process resulted in hiding more than desired in some cases, which is why I switched to the new version that iterates through all possibilities until it finds one that renders with no collisions.  But the problem with that approach is that sometimes every possibility has some collisions.   So I will need to change this new approach to keep track of the amount of collisions and remember the best possibility so far, or choose the first one that has no collisions.

Maybe you can shrink your tick font size so that more can be squeezed in.  There are also some other minimum spacing options for ticks.

**Comment by dlaliberte** [comment]
One thing about tick generation that the newer versions don't try is to reduce the required space between ticks.  So even if there are no collisions, there might not be enough space for any ticks if, for example, your height is so small that that there is not enough room for even 2 ticks.    The gridlines.minSpacing option defaults to 40 pixels, and minorGridlines.minSpacing defaults to half of whatever the major gridline minSpacing is.  (For log scales, it is different.)    See details in the release notes:    https://developers.google.com/chart/interactive/docs/release_notes#october-1,-2018
